stages:
  - build
  - qemu_test

variables:
  BATCH_BUILD: "1"
  V: "0"
  MAKEFLAGS: "-j5 --no-keep-going"
  GIT_SUBMODULE_STRATEGY: recursive
  QEMU_IMAGE: ${CI_DOCKER_REGISTRY}/qemu-v5.2:2-20230522

# before each job, we need to check if this job is filtered by bot stage/job filter
.apply_bot_filter: &apply_bot_filter
  python $APPLY_BOT_FILTER_SCRIPT || exit 0

.setup_env:
  before_script: &setup_env
    # apply bot filter in before script
    - *apply_bot_filter
    # add gitlab ssh key
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -n $GITLAB_KEY > ~/.ssh/id_rsa_base64
    - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host gitlab.espressif.cn\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - git --version
    - git submodule update --init --recursive

.build_idf_template:
  stage: build
  before_script: *setup_env
  image: espressif/idf:release-v5.5
  tags:
    - build
  parallel:
    matrix:
      - IDF_TARGET: esp32c3
        CONFIG: default
      - IDF_TARGET: esp32c3
        CONFIG: tlv
      - IDF_TARGET: esp32c3
        CONFIG: legacy
  variables:
    PEDANTIC_FLAGS: "-Werror -Werror=unused-variable -Werror=unused-but-set-variable -Werror=unused-function"
    EXTRA_CFLAGS: "${PEDANTIC_FLAGS}"
    EXTRA_CXXFLAGS: "${PEDANTIC_FLAGS}"
  script:
    - export EXTRA_CFLAGS=$EXTRA_CFLAGS
    - export EXTRA_CXXFLAGS=$EXTRA_CXXFLAGS
    - export ROOT_PATH=$PWD
    - cd $ROOT_PATH/test_apps
    - pip install -r $ROOT_PATH/test_apps/qemu_test/requirements.txt
    - idf-build-apps build --config "sdkconfig.ci.${CONFIG}" --target $IDF_TARGET --build-dir "build_${IDF_TARGET}_${CONFIG}"
  artifacts:
    paths:
      - test_apps/build_${IDF_TARGET}_${CONFIG}
    expire_in: 1 hour

.build_idf_template_release_v5.1:
  extends: .build_idf_template
  image: espressif/idf:release-v5.1

.build_idf_template_release_v5.2:
  extends: .build_idf_template
  image: espressif/idf:release-v5.2

.build_idf_template_release_v5.3:
  extends: .build_idf_template
  image: espressif/idf:release-v5.3

.build_idf_template_release_v5.4:
  extends: .build_idf_template
  image: espressif/idf:release-v5.4

.build_idf_template_release_v5.5:
  extends: .build_idf_template
  image: espressif/idf:release-v5.5

build_demo_esp32:
  extends: .build_idf_template
  parallel:
    matrix:
      - IDF_TARGET: esp32
        CONFIG: default
      - IDF_TARGET: esp32
        CONFIG: tlv
      - IDF_TARGET: esp32
        CONFIG: legacy

build_demo_esp32s3:
  extends: .build_idf_template
  parallel:
    matrix:
      - IDF_TARGET: esp32s3
        CONFIG: default
      - IDF_TARGET: esp32s3
        CONFIG: tlv
      - IDF_TARGET: esp32s3
        CONFIG: legacy

build_demo_esp32c3:
  extends: .build_idf_template
  parallel:
    matrix:
      - IDF_TARGET: esp32c3
        CONFIG: default
      - IDF_TARGET: esp32c3
        CONFIG: tlv
      - IDF_TARGET: esp32c3
        CONFIG: legacy
      - IDF_TARGET: esp32c3
        CONFIG: ecdsa_periperhal
      - IDF_TARGET: esp32c3
        CONFIG: rsa_ds

build_demo_esp32_v5.1:
  extends: .build_idf_template_release_v5.1
  parallel:
    matrix:
      - IDF_TARGET: esp32
        CONFIG: default
      - IDF_TARGET: esp32
        CONFIG: tlv
      - IDF_TARGET: esp32
        CONFIG: legacy

build_demo_esp32s3_v5.1:
  extends: .build_idf_template_release_v5.1
  parallel:
    matrix:
      - IDF_TARGET: esp32s3
        CONFIG: default
      - IDF_TARGET: esp32s3
        CONFIG: tlv
      - IDF_TARGET: esp32s3
        CONFIG: legacy

build_demo_esp32c3_v5.1:
  extends: .build_idf_template_release_v5.1
  parallel:
    matrix:
      - IDF_TARGET: esp32c3
        CONFIG: default
      - IDF_TARGET: esp32c3
        CONFIG: tlv
      - IDF_TARGET: esp32c3
        CONFIG: legacy

build_demo_esp32_v5.2:
  extends: .build_idf_template_release_v5.2
  parallel:
    matrix:
      - IDF_TARGET: esp32
        CONFIG: default
      - IDF_TARGET: esp32
        CONFIG: tlv
      - IDF_TARGET: esp32
        CONFIG: legacy

build_demo_esp32s3_v5.2:
  extends: .build_idf_template_release_v5.2
  parallel:
    matrix:
      - IDF_TARGET: esp32s3
        CONFIG: default
      - IDF_TARGET: esp32s3
        CONFIG: tlv
      - IDF_TARGET: esp32s3
        CONFIG: legacy

build_demo_esp32c3_v5.2:
  extends: .build_idf_template_release_v5.2
  parallel:
    matrix:
      - IDF_TARGET: esp32c3
        CONFIG: default
      - IDF_TARGET: esp32c3
        CONFIG: tlv
      - IDF_TARGET: esp32c3
        CONFIG: legacy

build_demo_esp32_v5.3:
  extends: .build_idf_template_release_v5.3
  parallel:
    matrix:
      - IDF_TARGET: esp32
        CONFIG: default
      - IDF_TARGET: esp32
        CONFIG: tlv
      - IDF_TARGET: esp32
        CONFIG: legacy

build_demo_esp32s3_v5.3:
  extends: .build_idf_template_release_v5.3
  parallel:
    matrix:
      - IDF_TARGET: esp32s3
        CONFIG: default
      - IDF_TARGET: esp32s3
        CONFIG: tlv
      - IDF_TARGET: esp32s3
        CONFIG: legacy

build_demo_esp32c3_v5.3:
  extends: .build_idf_template_release_v5.3
  parallel:
    matrix:
      - IDF_TARGET: esp32c3
        CONFIG: default
      - IDF_TARGET: esp32c3
        CONFIG: tlv
      - IDF_TARGET: esp32c3
        CONFIG: legacy

build_demo_esp32_v5.4:
  extends: .build_idf_template_release_v5.4
  parallel:
    matrix:
      - IDF_TARGET: esp32
        CONFIG: default
      - IDF_TARGET: esp32
        CONFIG: tlv
      - IDF_TARGET: esp32
        CONFIG: legacy

build_demo_esp32s3_v5.4:
  extends: .build_idf_template_release_v5.4
  parallel:
    matrix:
      - IDF_TARGET: esp32s3
        CONFIG: default
      - IDF_TARGET: esp32s3
        CONFIG: tlv
      - IDF_TARGET: esp32s3
        CONFIG: legacy

build_demo_esp32c3_v5.4:
  extends: .build_idf_template_release_v5.4
  parallel:
    matrix:
      - IDF_TARGET: esp32c3
        CONFIG: default
      - IDF_TARGET: esp32c3
        CONFIG: tlv
      - IDF_TARGET: esp32c3
        CONFIG: legacy

build_demo_esp32_v5.5:
  extends: .build_idf_template_release_v5.5
  parallel:
    matrix:
      - IDF_TARGET: esp32
        CONFIG: default
      - IDF_TARGET: esp32
        CONFIG: tlv
      - IDF_TARGET: esp32
        CONFIG: legacy

build_demo_esp32s3_v5.5:
  extends: .build_idf_template_release_v5.5
  parallel:
    matrix:
      - IDF_TARGET: esp32s3
        CONFIG: default
      - IDF_TARGET: esp32s3
        CONFIG: tlv
      - IDF_TARGET: esp32s3
        CONFIG: legacy

build_demo_esp32c3_v5.5:
  extends: .build_idf_template_release_v5.5
  parallel:
    matrix:
      - IDF_TARGET: esp32c3
        CONFIG: default
      - IDF_TARGET: esp32c3
        CONFIG: tlv
      - IDF_TARGET: esp32c3
        CONFIG: legacy

# Build job for examples app sanity test
build_examples_app_v5.5:
  extends: .build_idf_template_release_v5.5
  variables:
    IDF_TARGET: esp32c3
    CONFIG: examples
  script:
    - export EXTRA_CFLAGS=$EXTRA_CFLAGS
    - export EXTRA_CXXFLAGS=$EXTRA_CXXFLAGS
    - export ROOT_PATH=$PWD
    - cd $ROOT_PATH/examples/esp_secure_cert_app
    - pip install -r $ROOT_PATH/test_apps/qemu_test/requirements.txt
    - idf-build-apps build --target $IDF_TARGET --build-dir "build_${IDF_TARGET}_${CONFIG}"
  artifacts:
    paths:
      - examples/esp_secure_cert_app/build_${IDF_TARGET}_${CONFIG}
    expire_in: 1 hour

# Base QEMU test template with proper build directory handling
.qemu_test_base:
  stage: qemu_test
  tags:
    - qemu_test
  variables:
    IDF_TARGET: esp32c3  
    CONFIG: tlv          
  script:
    - export EXTRA_CFLAGS=$EXTRA_CFLAGS
    - export EXTRA_CXXFLAGS=$EXTRA_CXXFLAGS
    - export ROOT_PATH=$PWD
    - . $IDF_PATH/export.sh
    - cd $ROOT_PATH/test_apps
    - pip install -r $ROOT_PATH/test_apps/qemu_test/requirements.txt
    - export BUILD_DIR="build_${IDF_TARGET}_${CONFIG}"
    - pytest --target $IDF_TARGET --app-path $ROOT_PATH/test_apps --build-dir $BUILD_DIR

# QEMU test jobs for each ESP-IDF version with proper dependencies
qemu_test_tlv_esp32c3_v5.1:
  extends: .qemu_test_base
  image: espressif/idf:release-v5.1
  variables:
    IDF_TARGET: esp32c3  
    CONFIG: tlv          
  dependencies:
    - build_demo_esp32c3_v5.1

qemu_test_tlv_esp32c3_v5.2:
  extends: .qemu_test_base
  image: espressif/idf:release-v5.2
  variables:
    IDF_TARGET: esp32c3  
    CONFIG: tlv          
  dependencies:
    - build_demo_esp32c3_v5.2

qemu_test_tlv_esp32c3_v5.3:
  extends: .qemu_test_base
  image: espressif/idf:release-v5.3
  variables:
    IDF_TARGET: esp32c3  
    CONFIG: tlv          
  dependencies:
    - build_demo_esp32c3_v5.3

qemu_test_tlv_esp32c3_v5.4:
  extends: .qemu_test_base
  image: espressif/idf:release-v5.4
  variables:
    IDF_TARGET: esp32c3  
    CONFIG: tlv          
  dependencies:
    - build_demo_esp32c3_v5.4

qemu_test_tlv_esp32c3_v5.5:
  extends: .qemu_test_base
  image: espressif/idf:release-v5.5
  variables:
    IDF_TARGET: esp32c3  
    CONFIG: tlv          
  dependencies:
    - build_demo_esp32c3_v5.5

# QEMU test for examples app sanity test
qemu_test_examples_app_v5.5:
  stage: qemu_test
  image: espressif/idf:release-v5.5
  tags:
    - qemu_test
  variables:
    IDF_TARGET: esp32c3
    CONFIG: default
  script:
    - export EXTRA_CFLAGS=$EXTRA_CFLAGS
    - export EXTRA_CXXFLAGS=$EXTRA_CXXFLAGS
    - export ROOT_PATH=$PWD
    - . $IDF_PATH/export.sh
    - cd $ROOT_PATH/examples/esp_secure_cert_app
    - pip install -r $ROOT_PATH/test_apps/qemu_test/requirements.txt
    - export BUILD_DIR="build_${IDF_TARGET}_${CONFIG}"
    # Run the sanity test from examples app
    - pytest test_esp_secure_cert.py --target $IDF_TARGET --app-path . --build-dir $BUILD_DIR
  dependencies:
    - build_examples_app_v5.5
