name: PyPI release

on:
  push:
    branches:
      - main

jobs:
  build_and_upload:
    runs-on: ubuntu-22.04  # 22.04 is the last version with Python 3.7

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build setuptools twine
    - name: Build and upload esp-secure-cert-tool ${{ github.event.release.tag_name }}
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_PROJECT_TOKEN }}
      working-directory: ./tools
      run: |
        PUBLISHED_VERSION=$(curl https://pypi.org/pypi/esp-secure-cert-tool/json 2>/dev/null | jq -r '.info.version')
        CURRENT_VERSION=$(python setup.py --version 2>/dev/null)
        if [ "$PUBLISHED_VERSION" == "$CURRENT_VERSION" ]; then
          echo "Version ${PUBLISHED_VERSION} already published, skipping..."
          exit 0
        else
          echo "Packaging and publishing new esp-secure-cert-tool version: ${CURRENT_VERSION}"
          python setup.py sdist
          tar -ztvf dist/*
          twine upload dist/*
        fi
