name: Push esp_secure_cert_mgr to Espressif Component Service

on:
  push:
    branches:
      - main

jobs:
  upload_components:
    runs-on: ubuntu-22.04  # 22.04 is the last version with Python 3.7
    steps:
      - uses: actions/checkout@v2

      - name: Upload esp_secure_cert_mgr to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          name: esp_secure_cert_mgr
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
